// Mock Data

const tools: Tool[] = [
  {
    id: "terminal",
    name: "Smart Terminal",
    description: "AI-powered command line interface with predictive suggestions",
    icon: <Terminal className="w-6 h-6" />,
    category: "core",
    popularity: 98,
  },
  {
    id: "debugger",
    name: "Visual Debugger",
    description: "Time-travel debugging with state inspection",
    icon: <Boxes className="w-6 h-6" />,
    category: "debug",
    popularity: 92,
  },
  {
    id: "git",
    name: "Git Control",
    description: "Advanced version control with merge visualization",
    icon: <GitBranch className="w-6 h-6" />,
    category: "core",
    popularity: 95,
  },
  {
    id: "compiler",
    name: "Smart Compiler 2.33",
    description: "Intelligent code compilation with error prediction",
    icon: <Cpu className="w-6 h-6" />,
    category: "build",
    popularity: 88,
  },
  {
    id: "syntax",
    name: "Syntax Analyzer 2.42",
    description: "Real-time code analysis and optimization suggestions",
    icon: <Braces className="w-6 h-6" />,
    category: "debug",
    popularity: 90,
  },
  {
    id: "ai",
    name: "AI Assistant 2.42",
    description: "Context-aware code completion and refactoring",
    icon: <Sparkles className="w-6 h-6" />,
    category: "build",
    popularity: 94,
  },
  {
    id: "ai-beta",
    name: "AI Assistant 2.58",
    description: "Next-gen AI with advanced semantic code understanding and real-time pair programming",
    icon: <Sparkles className="w-6 h-6" />,
    category: "build",
    popularity: 96,
  },
  {
    id: "ai-experimental",
    name: "AI Assistant 2.599",
    description: "Experimental build with quantum-inspired code synthesis and multi-model reasoning",
    icon: <Sparkles className="w-6 h-6" />,
    category: "build",
    popularity: 97,
  },
  {
    id: "ai-nightly",
    name: "AI Assistant 2.599",
    description: "Nightly build with advanced neural architecture and predictive code generation",
    icon: <Sparkles className="w-6 h-6" />,
    category: "build",
    popularity: 98,
  },
];
