// ... keep existing code (imports, interfaces, and other tools)

const tools: Tool[] = [
  {
    id: "terminal",
    name: "Smart Terminal",
    description: "AI-powered command line interface with predictive suggestions",
    icon: <Terminal className="w-6 h-6" />,
    category: "core",
    popularity: 98,
    downloads: 50000,
    lastUpdate: "2024-01-15",
  },
  {
    id: "debugger",
    name: "Visual Debugger",
    description: "Time-travel debugging with state inspection",
    icon: <Boxes className="w-6 h-6" />,
    category: "debug",
    popularity: 92,
    downloads: 35000,
    lastUpdate: "2024-01-10",
  },
  {
    id: "git",
    name: "Git Control",
    description: "Advanced version control with merge visualization",
    icon: <GitBranch className="w-6 h-6" />,
    category: "core",
    popularity: 95,
    downloads: 45000,
    lastUpdate: "2024-01-12",
  },
  {
    id: "compiler",
    name: "Smart Compiler 2.33",
    description: "Intelligent code compilation with error prediction",
    icon: <Cpu className="w-6 h-6" />,
    category: "build",
    popularity: 88,
    downloads: 30000,
    lastUpdate: "2024-01-08",
  },
  {
    id: "syntax",
    name: "Syntax Analyzer",
    description: "Real-time code analysis and optimization suggestions",
    icon: <Braces className="w-6 h-6" />,
    category: "debug",
    popularity: 90,
    downloads: 40000,
    lastUpdate: "2024-01-14",
  },
  {
    id: "ai",
    name: "AI Assistant",
    description: "Context-aware code completion and refactoring",
    icon: <Sparkles className="w-6 h-6" />,
    category: "build",
    popularity: 94,
    downloads: 48000,
    lastUpdate: "2024-01-13",
  },
];

// ... keep existing code (rest of the components and main Index component)